# Generated by Django 5.1.15 on 2026-05-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_feature_flags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="htx_quality_status_94ec08_idx",
            old_name="htx_qa_status_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="htx_quality_severit_656cfa_idx",
            old_name="htx_qa_severity_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="htx_quality_trigger_080723_idx",
            old_name="htx_qa_trigger_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="htx_quality_trainer_c73fc3_idx",
            old_name="htx_qa_trainer_idx",
        ),
    ]
