// TrainPlex k6 — shared login helper.
//
// Used by every scenario script under `scenarios/`. Performs a single
// session login against `/user/login/` (CSRF-aware) and returns the
// session cookie jar so subsequent requests authenticate transparently.
//
// Why a shared helper:
//   * Login is the most frequent hot-path call in every scenario; one
//     bug here (e.g. CSRF token reused across users) would invalidate
//     every other measurement.
//   * Keeps each scenario file focused on the workload under test
//     instead of repeating session bootstrap code.
//
// k6 contract:
//   * Default export from a script is the "virtual user" function. We
//     instead expose `loginAs(email, password)` so the scenario chooses
//     whether to log in per-VU (long-lived) or per-iteration (login_burst).
//   * Cookies live on `http.cookieJar()` by default — k6 attaches them
//     automatically on follow-up requests from the same VU.
//
// Founder rule honoured:
//   * No founder personal number is ever passed to this helper; emails
//     are synthetic `trainerNNN@loadtest.trainplex.in` from the runner.

import http from 'k6/http';
import { check, fail } from 'k6';

// `BASE` defaults to the staging host; override in CLI: `-e BASE=https://...`
export const BASE = __ENV.BASE || 'https://staging.trainplex.in';

// Synthetic user pool — generated by the loadtest seed script (not in this
// repo). Each scenario picks a user via a random or modulo index so we
// don't hammer one account.
export const TRAINER_POOL_SIZE = 100;
export const ADMIN_POOL_SIZE = 5;

/**
 * Pick a synthetic trainer email from the deterministic pool.
 *
 * @param {number} idx VU iteration counter (any integer; we modulo it).
 * @returns {string} `trainer042@loadtest.trainplex.in`
 */
export function pickTrainer(idx) {
  const i = ((idx % TRAINER_POOL_SIZE) + TRAINER_POOL_SIZE) % TRAINER_POOL_SIZE;
  return `trainer${String(i).padStart(3, '0')}@loadtest.trainplex.in`;
}

/**
 * Pick a synthetic admin email from a smaller deterministic pool.
 *
 * @param {number} idx VU iteration counter.
 * @returns {string} `admin02@loadtest.trainplex.in`
 */
export function pickAdmin(idx) {
  const i = ((idx % ADMIN_POOL_SIZE) + ADMIN_POOL_SIZE) % ADMIN_POOL_SIZE;
  return `admin${String(i).padStart(2, '0')}@loadtest.trainplex.in`;
}

/**
 * Log in as `email` and return the session token (cookies on jar).
 *
 * Two-step flow because Django's login enforces CSRF:
 *   1. GET /user/login/ → scrape `csrfmiddlewaretoken` from form HTML
 *   2. POST /user/login/ with email + password + that token
 *
 * Throws (k6 `fail`) on non-2xx so the iteration is marked failed.
 *
 * @param {string} email
 * @param {string} password fixed `LoadTest2026!` across the synthetic pool
 * @returns {{ jar: object, csrf: string }}
 */
export function loginAs(email, password) {
  const pw = password || __ENV.LOADTEST_PASSWORD || 'LoadTest2026!';
  const jar = http.cookieJar();

  // Step 1 — fetch login page to mint CSRF token + cookie
  const getRes = http.get(`${BASE}/user/login/`, { tags: { name: 'login_get' } });
  check(getRes, { 'login GET 200': (r) => r.status === 200 }) ||
    fail(`login GET failed for ${email}: ${getRes.status}`);

  // Hand-rolled scrape (no JSDOM in k6). CSRF token is a 64-char hex/base64
  // in a hidden input — single regex is plenty fast and avoids pulling in
  // a parser dependency.
  const csrfMatch = getRes.body.match(
    /name=["']csrfmiddlewaretoken["']\s+value=["']([^"']+)["']/i,
  );
  if (!csrfMatch) {
    fail(`csrf token not found in login page for ${email}`);
  }
  const csrf = csrfMatch[1];

  // Step 2 — submit credentials
  const postRes = http.post(
    `${BASE}/user/login/`,
    {
      csrfmiddlewaretoken: csrf,
      email,
      password: pw,
    },
    {
      headers: {
        Referer: `${BASE}/user/login/`,
      },
      tags: { name: 'login_post' },
      redirects: 0, // we want to see the 302 explicitly
    },
  );
  check(postRes, {
    'login POST 302': (r) => r.status === 302,
    'login POST not 401': (r) => r.status !== 401,
  }) || fail(`login POST failed for ${email}: ${postRes.status} body=${postRes.body?.slice(0, 200)}`);

  return { jar, csrf };
}

/**
 * Shared k6 thresholds applied to every scenario.
 *
 * Per Week-8 deliverable: p95 < 500ms for /api/v1/*, p99 < 1000ms,
 * error rate < 1% at 10x current scale.
 */
export const SHARED_THRESHOLDS = {
  http_req_duration: ['p(95)<500', 'p(99)<1000'],
  http_req_failed: ['rate<0.01'],
  // Per-endpoint sub-budgets for the hot path. k6 lets us tag any request
  // and threshold on the tag — keeps the dashboard readable.
  'http_req_duration{name:trainer_batch_get}': ['p(95)<300'],
  'http_req_duration{name:submit}': ['p(95)<600'],
  'http_req_duration{name:dashboard_snapshot}': ['p(95)<400'],
};
