# Generated by Django 5.1.15 on 2026-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_custom_hotkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("trainer", "Trainer"),
                    ("reviewer", "Reviewer"),
                    ("qa_lead", "QA Lead"),
                    ("admin", "Admin"),
                ],
                default="trainer",
                help_text="TrainPlex role for RBAC",
                max_length=20,
            ),
        ),
    ]
