# Generated by Django 5.1.15 on 2026-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_first_class_profile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="htx_audit_l_user_id_2b6762_idx",
            old_name="htx_audit_l_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="htx_audit_l_action_73ca8e_idx",
            old_name="htx_audit_l_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="htx_audit_l_created_e97c72_idx",
            old_name="htx_audit_l_created_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trainer profile: city.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="Trainer profile: preferred UI language.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pincode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trainer profile: postal pincode.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trainer profile: Indian state.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tier",
            field=models.CharField(
                blank=True,
                default="bronze",
                help_text="Trainer profile: tier badge.",
                max_length=16,
            ),
        ),
    ]
